trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
  platformOperationServiceConnection: 3MInfraConnection
  locationName: centralus
stages:
  - stage: newEnv
    displayName: New Environment
    dependsOn: []
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: Visual Studio Enterprise Subscription – MPN
          locationName: $(locationName)
          environmentName: IoT_Demo
          subscriptionId: d2413346-1d72-4ae7-8969-64fbdf906cf8
          applicationCode: iotdemo
          applicationShortCode: iotd
          environmentCategory: test
          platformOperationServiceConnection: $(platformOperationServiceConnection)
          k8sVersion: 1.16.7